[package]
name = "key_storage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusqlite = "0.28.0"
orion = "0.15.5"
blake3 = "1.3.3"
sodiumoxide = "0.2.7"
passwords = "3.1.12"
